[package]
name = "fs-ffi-py"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]
name = "fusion_store"

[dependencies]
fs-core = { path = "../fs-core" }
pyo3 = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
